#!/usr/bin/env node
// Rumble framework renderer — one canonical process, rendered per runtime into a project.
//
//   node render.mjs <project-dir>            write the generated files
//   node render.mjs <project-dir> --check    exit 1 and name every file that drifted
//
// The project declares itself in <project-dir>/framework.json (see examples/). Everything
// generated carries a "generated" banner; edit framework/ or framework.json, never the output.
// Dependency-free on purpose (Node ≥ 18): the same rule as design tokens — one source, checked in
// outputs, a check that fails on drift.

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const check = args.includes('--check');
const projectDir = resolve(args.find(a => !a.startsWith('--')) || '.');
const configPath = join(projectDir, 'framework.json');
if (!existsSync(configPath)) { console.error(`no framework.json in ${projectDir}`); process.exit(2); }
const cfg = JSON.parse(readFileSync(configPath, 'utf8'));

const read = p => readFileSync(join(HERE, p), 'utf8');
const bannerFor = (ext, src) => {
  const line = `generated by rumble-framework from ${src} — edit framework.json or the framework, not this file`;
  if (ext === '.toml') return `# ${line}\n`;
  if (ext === '.json') return '';
  return `<!-- ${line} -->\n`;
};
// frontmatter must stay on line 1 (Claude Code and Codex both parse it there): the banner goes after it
const withBanner = (content, ext, src) => {
  const b = bannerFor(ext, src);
  if (ext === '.md' && content.startsWith('---\n')) {
    const close = content.indexOf('\n---\n', 4);
    if (close > 0) { const at = close + 5; return content.slice(0, at) + b + content.slice(at); }
  }
  return b + content;
};

// ---------- tiny template engine: {{a.b}}, {{#if a}}…{{/if}}, {{#each list}}…{{/each}} ----------
function get(ctx, path) {
  if (path === '.') return ctx['.'];
  return path.split('.').reduce((o, k) => (o == null ? undefined : o[k]), ctx);
}
function render(tpl, ctx) {
  tpl = tpl.replace(/\{\{#each ([\w.]+)\}\}([\s\S]*?)\{\{\/each\}\}/g, (_, path, body) => {
    const list = get(ctx, path) || [];
    return list.map((item, i) => render(body, { ...ctx, '.': item, item, index: i, last: i === list.length - 1 })).join('');
  });
  tpl = tpl.replace(/\{\{#if ([\w.]+)\}\}([\s\S]*?)(?:\{\{else\}\}([\s\S]*?))?\{\{\/if\}\}/g, (_, path, a, b = '') => (get(ctx, path) ? render(a, ctx) : render(b, ctx)));
  tpl = tpl.replace(/\{\{([\w.]+)\}\}/g, (m, path) => { const v = get(ctx, path); if (v === undefined) throw new Error(`unresolved {{${path}}}`); return typeof v === 'string' ? v : JSON.stringify(v); });
  return tpl;
}

// ---------- build the context for one runtime ----------
function contextFor(binding) {
  const stages = {};
  for (const [k, v] of Object.entries(binding.stages)) {
    if (typeof v === 'string') { stages[k] = v; continue; }
    const tier = (cfg.stage_overrides && cfg.stage_overrides[k]) || v.tier;
    stages[k] = { tier, model: binding.models[tier], effort: v.effort || '' };
  }
  const implementers = (cfg.implementers || []).map(i => ({ ...i, areas_line: i.areas.map(a => `\`${a}\``).join(' · ') }));
  const areas = (cfg.areas || []).map(a => ({ ...a }));
  const mandatory = (cfg.mandatory_suites || []).map(s => ({ ...s, when_line: s.when_paths.map(p => `\`${p}\``).join(', ') }));
  return {
    project: cfg.project, repo: cfg.repo, owner: cfg.owner, human: cfg.human || cfg.owner,
    runtime: { ...binding, stages },
    labels: cfg.labels, areas, risk_high: cfg.risk_high, verify: cfg.verify, docs: cfg.docs,
    implementers, mandatory: mandatory, has_mandatory: mandatory.length > 0,
    limits: Object.assign({ parallel_builders: 3, fix_rounds: 2, split_lines: 3000, disk_floor_gb: 80 }, cfg.limits || {}),
    project_notes: cfg.project_notes || {},
    gate: { merge: (cfg.gate && cfg.gate.merge) || 'orchestrator', human_merges: !!(cfg.gate && cfg.gate.merge === 'human') },
    agents: { security: (cfg.agent_names && cfg.agent_names.security) || 'sec-reviewer' },
  };
}

// ---------- outputs ----------
const outputs = [];            // { path, content }
function emit(relPath, content) { outputs.push({ path: relPath, content }); }

for (const rtName of cfg.runtimes) {
  const binding = JSON.parse(read(`bindings/${rtName}.json`));
  const ctx = contextFor(binding);
  const agentTpl = read(`templates/${binding.agent_template}`);

  // agents: the five roles, implementers expanded per project implementer
  const roles = ['triage', 'architect', 'quality-reviewer', 'security-reviewer'];
  const agentSpecs = [];
  for (const role of roles) {
    const body = render(read(`framework/agents/${role}.md`), ctx);
    const st = role === 'triage' ? ctx.runtime.stages.triage : role === 'architect' ? ctx.runtime.stages.architect : ctx.runtime.stages.review;
    const tools = role === 'architect' ? 'web' : role === 'security-reviewer' ? 'web' : 'read';
    agentSpecs.push({ name: role === 'security-reviewer' ? ctx.agents.security : role, description: firstLine(body), model: st.model, effort: st.effort, tools: binding.tools?.[tools] || '', sandbox: binding.sandbox?.[tools] || '', body: stripFirstLine(body) });
  }
  for (const impl of ctx.implementers) {
    const body = render(read('framework/agents/implementer.md'), { ...ctx, impl });
    // one file per implementer per size tier the binding distinguishes (codex needs a model per size)
    const sizes = binding.name === 'codex' ? ['S', 'M', 'L'] : [null];
    for (const size of sizes) {
      const st = size ? ctx.runtime.stages[size] : ctx.runtime.stages.M;
      agentSpecs.push({ name: size ? `${impl.name}-${size.toLowerCase()}` : impl.name, description: firstLine(body) + (size ? ` (size:${size})` : ''), model: st.model, effort: st.effort, tools: binding.tools?.write || '', sandbox: binding.sandbox?.write || '', body: stripFirstLine(body) });
    }
  }
  for (const a of agentSpecs) {
    const content = withBanner(render(agentTpl, { agent: a }), binding.agent_ext, 'framework/agents');
    emit(join(binding.agents_dir, a.name + binding.agent_ext), content);
  }

  // skills: same SKILL.md format on both runtimes
  for (const skill of ['pipeline', 'task-out']) {
    const body = render(read(`framework/process/${skill}.md`), ctx);
    emit(join(binding.skills_dir, skill, 'SKILL.md'), withBanner(body, '.md', `framework/process/${skill}.md`));
  }

  // the managed block inside the project's guide file (CLAUDE.md / AGENTS.md)
  const block = render(read('framework/process/guide-block.md'), ctx);
  const guidePath = join(projectDir, binding.guide_file);
  const begin = '<!-- rumble-framework:begin -->', end = '<!-- rumble-framework:end -->';
  const existing = existsSync(guidePath) ? readFileSync(guidePath, 'utf8') : `# ${cfg.project} — agent guide\n\n${begin}\n${end}\n`;
  if (!existing.includes(begin) || !existing.includes(end)) {
    console.error(`${binding.guide_file}: add the managed block markers ${begin} … ${end} where the framework section belongs`); process.exit(2);
  }
  const merged = existing.replace(new RegExp(`${begin}[\\s\\S]*?${end}`), `${begin}\n${block.trim()}\n${end}`);
  emit(binding.guide_file, merged);
}

// the standards: framework core + the project's own sections, at the project's path
{
  const anyBinding = JSON.parse(read(`bindings/${cfg.runtimes[0]}.json`));
  const ctx = contextFor(anyBinding);
  const projectSections = cfg.standards_project_sections ? readFileSync(join(projectDir, cfg.standards_project_sections), 'utf8') : '';
  const core = render(read('framework/standards/engineering-standards.core.md'), { ...ctx, project_sections: projectSections });
  emit(cfg.docs.standards, bannerFor('.md', 'framework/standards + ' + (cfg.standards_project_sections || 'no project sections')) + core);
}

// ---------- write or check ----------
let drift = 0;
for (const o of outputs) {
  const p = join(projectDir, o.path);
  const cur = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (check) { if (cur !== o.content) { drift++; console.log(`drift: ${o.path}${cur === null ? ' (missing)' : ''}`); } }
  else { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, o.content); console.log(`wrote ${o.path}`); }
}
if (check) { console.log(drift ? `${drift} file(s) drifted` : `framework: ${outputs.length} generated files match`); process.exit(drift ? 1 : 0); }

function firstLine(s) { return s.split('\n').find(l => l.trim())?.replace(/^#+\s*/, '').trim() || ''; }
function stripFirstLine(s) { const lines = s.split('\n'); const i = lines.findIndex(l => l.trim()); return lines.slice(i + 1).join('\n').trim() + '\n'; }
